const languages = [
    { code: "af-ZA", name: "Afrikaans (South Africa)" },
    { code: "sq-AL", name: "Albanian (Albania)" },
    { code: "am-ET", name: "Amharic (Ethiopia)" },
    { code: "ar-SA", name: "Arabic (Saudi Arabia)" },
    { code: "hy-AM", name: "Armenian (Armenia)" },
    { code: "az-AZ", name: "Azerbaijani (Azerbaijan)" },
    { code: "bn-BD", name: "Bengali (Bangladesh)" },
    { code: "bn-IN", name: "Bengali (India)" },
    { code: "en-US", name: "English (United States)" },
    { code: "en-GB", name: "English (United Kingdom)" },
    { code: "en-AU", name: "English (Australia)" },
    { code: "en-CA", name: "English (Canada)" },
    { code: "en-IN", name: "English (India)" },
    { code: "fr-FR", name: "French (France)" },
    { code: "fr-CA", name: "French (Canada)" },
    { code: "de-DE", name: "German (Germany)" },
    { code: "el-GR", name: "Greek (Greece)" },
    { code: "gu-IN", name: "Gujarati (India)" },
    { code: "hi-IN", name: "Hindi (India)" },
    { code: "id-ID", name: "Indonesian (Indonesia)" },
    { code: "it-IT", name: "Italian (Italy)" },
    { code: "ja-JP", name: "Japanese (Japan)" },
    { code: "jv-ID", name: "Javanese (Indonesia)" },
    { code: "kn-IN", name: "Kannada (India)" },
    { code: "ko-KR", name: "Korean (South Korea)" },
    { code: "ml-IN", name: "Malayalam (India)" },
    { code: "mr-IN", name: "Marathi (India)" },
    { code: "ne-NP", name: "Nepali (Nepal)" },
    { code: "pa-IN", name: "Punjabi (India)" },
    { code: "pl-PL", name: "Polish (Poland)" },
    { code: "pt-BR", name: "Portuguese (Brazil)" },
    { code: "pt-PT", name: "Portuguese (Portugal)" },
    { code: "ro-RO", name: "Romanian (Romania)" },
    { code: "ru-RU", name: "Russian (Russia)" },
    { code: "sr-RS", name: "Serbian (Serbia)" },
    { code: "es-ES", name: "Spanish (Spain)" },
    { code: "es-MX", name: "Spanish (Mexico)" },
    { code: "ta-IN", name: "Tamil (India)" },
    { code: "te-IN", name: "Telugu (India)" },
    { code: "th-TH", name: "Thai (Thailand)" },
    { code: "tr-TR", name: "Turkish (Turkey)" },
    { code: "uk-UA", name: "Ukrainian (Ukraine)" },
    { code: "ur-PK", name: "Urdu (Pakistan)" },
    { code: "vi-VN", name: "Vietnamese (Vietnam)" },
    { code: "zh-CN", name: "Chinese, Mandarin (Simplified, China)" },
    { code: "zh-HK", name: "Chinese, Cantonese (Traditional, Hong Kong)" },
    { code: "zh-TW", name: "Chinese, Mandarin (Traditional, Taiwan)" }
  ];

  export default languages;
  